(defun refe2x (kw)
  (interactive "sReFe2x: ")
  (let ((coding-system-for-read 'euc-japan))
    (with-current-buffer (get-buffer-create (concat "*refe2x:" kw "*"))
      (when (zerop (buffer-size))
        (call-process "refe2x" nil t t kw)
        (diff-mode))
      (setq minibuffer-scroll-window (get-buffer-window (current-buffer) t))
      (goto-char (point-min))
      (display-buffer (current-buffer)))))
