(defvar canna-mode-map (make-sparse-keymap))

(define-key canna-mode-map [right] "\C-l")
(define-key canna-mode-map [left] "\C-k")
(define-key canna-mode-map [down] "\C-n")
(define-key canna-mode-map [f6] "\C-u")
(define-key canna-mode-map [f7] "\C-i")
(define-key canna-mode-map [f8] "\C-o")
(define-key canna-mode-map [f9] "\C-p")
(define-key canna-minibuffer-mode-map [right] "\C-l")
(define-key canna-minibuffer-mode-map [left] "\C-k")
(define-key canna-minibuffer-mode-map [down] "\C-n")
(define-key canna-minibuffer-mode-map [f6] "\C-u")
(define-key canna-minibuffer-mode-map [f7] "\C-i")
(define-key canna-minibuffer-mode-map [f8] "\C-o")
(define-key canna-minibuffer-mode-map [f9] "\C-p")
