;(autoload 'html-mode "html-mode" "HTML mode" t)
;(autoload 'html-mode "html-mode" nil t)
;(setq auto-mode-alist (cons '("\\.html$" . html-mode) 
;                              auto-mode-alist))
(autoload 'hm--html-mode "hm--html-mode" "HTML major mode." t)
(autoload 'hm--html-minor-mode "hm--html-mode" "HTML minor mode." t)
(or (assoc "\\.html$" auto-mode-alist)
(setq auto-mode-alist (cons '("\\.html$" . hm--html-mode)
          				auto-mode-alist)))
(setq hm--html-changed-comment-prefix "")
(setq hm--html-automatic-changed-comment nil)
